apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ecsdemo-frontend
  namespace: argocd
spec:
  destinations:
  - namespace: ecsdemo-frontend
    server: https://kubernetes.default.svc
  sourceRepos:
  - git@github.com:bigben80/ecsdemo-frontend.git
